---
#
# Install/run nginx
#

# satisfy package dependencies
- name: Check for epel
  shell: rpm -qa | grep -q epel-release
  ignore_errors: true
  register: epel_installed

- name: Install epel repo
  command: rpm -ivh {{ epel_repo }}
  become: true
  when: epel_installed.rc != 0

- name: Install nginx rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - nginx 

# deploy kibana.conf with FQDN
- name: setup nginx reverse proxy for kibana
  template:
    src=kibana.conf.j2
    dest=/etc/nginx/conf.d/kibana.conf
    owner=root
    group=root
    mode=0644
  become: true
  register: nginx_needs_restart

# start nginx service
- name: Start nginx service
  command: systemctl start nginx.service
  ignore_errors: true
  when: nginx_needs_restart != 0 

# determine firewall status and take action
# 1) use firewall-cmd if firewalld is utilized
# 2) insert iptables rule if iptables is used

# Firewalld 
- name: Determine if firewalld is in use
  shell: systemctl is-enabled firewalld.service | egrep -qv 'masked|disabled'
  ignore_errors: true
  register: firewalld_in_use  

- name: Determine if firewalld is active
  shell: systemctl is-active firewalld.service | grep -vq inactive
  ignore_errors: true
  register: firewalld_is_active

- name: Determine if TCP/80 is already active
  shell: firewall-cmd --list-ports | egrep -q "^80/tcp"
  ignore_errors: true
  register: firewalld_tcp80_exists

# add firewall rule via firewall-cmd
- name: Add firewall rule for TCP/80 (firewalld)
  command: "{{ item }}" 
  with_items:
    - firewall-cmd --zone=public --add-port=80/tcp --permanent
    - firewall-cmd --reload
  ignore_errors: true
  become: true
  when: firewalld_in_use.rc == 0 and firewalld_is_active.rc == 0 and firewalld_tcp80_exists.rc != 0 

# iptables-services
- name: check firewall rules for TCP/80 (iptables-services)
  shell: grep "dport 80 \-j ACCEPT" /etc/sysconfig/iptables | wc -l
  ignore_errors: true
  register: iptables_tcp80_exists
  failed_when: iptables_tcp80_exists == 127

- name: Add firewall rule for TCP/80 (iptables-services)
  lineinfile: 
    dest: /etc/sysconfig/iptables 
    line: '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
    regexp: '^INPUT -i lo -j ACCEPT'
    insertbefore: '-A INPUT -i lo -j ACCEPT'
    backup: yes
  when: firewalld_in_use.rc != 0 and firewalld_is_active.rc != 0 and iptables_tcp80_exists.stdout|int == 0
  register: iptables_needs_restart

- name: Restart iptables-services for TCP/80 (iptables-services)
  shell: systemctl restart iptables.service
  ignore_errors: true
  when: iptables_needs_restart != 0 and firewalld_in_use.rc != 0 and firewalld_is_active.rc != 0
